/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@/http/core'

// 控制器名称
const controller = 'app'
const service = ''
const gateway = 'default'

export const AppController = {
    // 获取系统基本信息
    appBase: {
        gateway,
        service,
        controller,
        path: '/api/weapp/app/app-base',
        type: RequestMethod.Get
    },
    // 用户登录
    login: {
        gateway,
        service,
        controller,
        path: '/api/weapp/app/login',
        type: RequestMethod.Get
    },
    // 刷新Token
    token: {
        gateway,
        service,
        controller,
        path: '/api/weapp/app/token',
        type: RequestMethod.Get
    },
    // 获取当前用户信息
    getCurrentUser: {
        gateway,
        service,
        controller,
        path: '/api/weapp/app/current',
        type: RequestMethod.Get
    }
}
