/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@/http/core'

// 控制器名称
const controller = 'banner'
const service = ''
const gateway = 'default'

export const BannerController = {
  // 查询Banner列表
  findBanner: {
    gateway,
    service,
    controller,
    path: '/api/weapp/banner',
    type: RequestMethod.Get,
  },
}
