/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestAction, RequestParams } from '@/http/core'
import type { Observable } from 'rxjs'
import { QiniuController } from '@/http/controllers/qiniu.controller'
import { GetUploadTokenResponse } from '@/http/model'

export class QiniuService {
    /**
     *
     */
    @RequestAction({
        server: QiniuController.getUploadToken
    })
    public getUploadToken(
        params?: RequestParams | { [key: string]: any }
    ): Observable<GetUploadTokenResponse> {
        return RequestParams.create(params).request()
    }
}
